### PR TITLE
Try to resolve any reference

### LINKED ISSUE #475: Resolving jdt URLs inside jdt buffers
## Summary

Navigating from a `.java` to a `jdt://*` URL works, but opening another `jdt://*` reference inside an `jdt://*` buffer fails:

```
Error: ErrorMessage { msg: "Failed to convert from path (\"jdt://contents/rt.jar/java.lang/System.class?=sample-java/%5C/Library%5C/Java%5C/JavaVirtualMachines%5C/jdk1.8.0_92.jdk%5C/Contents%5C/Home%5C/jre%5C/lib%5C/rt.jar%3Cjava.lang(System.class\") to Url" }
```  

## Reproduction
- neovim/vim version: v0.3.1-9-gf27a665e0
- This plugin version: 9a316ef
- This plugin's binary version: 0.1.88 9a316ef9f044674724b44cd162f3996113ea4861
- Language server link and version: [eclipse.jdt.ls](https://github.com/eclipse/eclipse.jdt.ls)
- Steps to reproduce the issue from clean state
    1. Open [App.java](https://github.com/autozimu/LanguageClient-neovim/blob/next/tests/data/sample-java/src/main/java/app/App.java)
    2. Jump to definition of System.__out__ (Line 11)
    3. Jump to another definition (e.g. `PrintStream`)
- Logs:
[LanguageClient.log](https://github.com/autozimu/LanguageClient-neovim/files/2108916/LanguageClient.log)

## Current Behavior

Jump to definition via `*.java` -> `jdt://*` -> `jdt://*` fails

## Expected Behavior

Jump to definition via `*.java` -> `jdt://*` -> `jdt://*` works

### PR DESCRIPTION
**Pull request by tbo**
This closes #475.

### CODE REVIEW

File: src/utils.rs [hunk 1]
```diff
@@ -120,12 +120,14 @@ pub trait ToUrl {
...
 impl<P: AsRef<Path> + std::fmt::Debug> ToUrl for P {
     fn to_url(&self) -> Result<Url> {
-        Url::from_file_path(self).or_else(|_| {
-            Err(format_err!(
-                "Failed to convert from path ({:?}) to Url",
-                self
-            ))
-        })
+        Url::from_file_path(self).or_else(|_| (
+            Url::from_str(self.as_ref().to_str().unwrap()).or_else(|_| {
```
Comment (autozimu) [inline src/utils.rs]: `.unwrap()` on a `None` will be a hard crash.

Please use `Url::from_str(&self.as_ref().to_string_lossy())` instead.

**Comment by autozimu** [comment]
Thanks.
